version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      POSTGRES_DB: dbp
      PGUSER: postgres
      PGPASSWORD: 123

  http-server:
    image: node:10.16.0
    working_dir: /usr/src/app
    volumes:
      - ./src/main/resources/static:/usr/src/app
    command: sh -c "npm install -g http-server@0.12.3 && http-server -p 8085" 
    ports:
      - "8085:8085"
